PUT http://localhost:3000/users
Content-Type: application/json

{
  "_id": "63d3a52bab3fb7ab951e1a9e",
  "id": "user1",
  "password": "password123",
  "type": "Organizer",
  "firstname": "John",
  "lastname": "Doe",
  "age": 30,
  "address": "123 Secondary St"
}